# Generated by Django 4.1.7 on 2023-05-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_creditapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='call_made',
            field=models.BooleanField(default=False),
        ),
    ]
